//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileLockCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileLockCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied (Admin rights required).
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string CaptionInformation {
            get {
                return ResourceManager.GetString("CaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string CaptionSuccess {
            get {
                return ResourceManager.GetString("CaptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating XML data: {0}.
        /// </summary>
        public static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information for blocking processes has been copied to clipboard..
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show locked files.
        /// </summary>
        public static string ExpanderLockedFiles {
            get {
                return ResourceManager.GetString("ExpanderLockedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Lock Check.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to forcefully close &apos;{0}&apos;? Unsaved data will be lost..
        /// </summary>
        public static string KillConfirmMessage {
            get {
                return ResourceManager.GetString("KillConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Kill.
        /// </summary>
        public static string KillConfirmTitle {
            get {
                return ResourceManager.GetString("KillConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string KillErrorTitle {
            get {
                return ResourceManager.GetString("KillErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Process.
        /// </summary>
        public static string KillProcessButton {
            get {
                return ResourceManager.GetString("KillProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locking process details to copy..
        /// </summary>
        public static string NoProcessData {
            get {
                return ResourceManager.GetString("NoProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title.
        /// </summary>
        public static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM:.
        /// </summary>
        public static string RamLabel {
            get {
                return ResourceManager.GetString("RamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to fully apply the language changes to the main window..
        /// </summary>
        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string RestartRequiredTitle {
            get {
                return ResourceManager.GetString("RestartRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected File:.
        /// </summary>
        public static string SelectedFileLabel {
            get {
                return ResourceManager.GetString("SelectedFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Shortcut:.
        /// </summary>
        public static string ShortcutLabel {
            get {
                return ResourceManager.GetString("ShortcutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here and press your desired key combination.
        /// </summary>
        public static string ShortcutTooltip {
            get {
                return ResourceManager.GetString("ShortcutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} process(es) locking this file:.
        /// </summary>
        public static string StatusLockedFormat {
            get {
                return ResourceManager.GetString("StatusLockedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected in Explorer..
        /// </summary>
        public static string StatusNoFileSelected {
            get {
                return ResourceManager.GetString("StatusNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not currently locked by any process..
        /// </summary>
        public static string StatusNotLocked {
            get {
                return ResourceManager.GetString("StatusNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file in an active Windows Explorer window..
        /// </summary>
        public static string StatusPleaseSelectFile {
            get {
                return ResourceManager.GetString("StatusPleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayExitItem {
            get {
                return ResourceManager.GetString("TrayExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileLockCheck ({0}).
        /// </summary>
        public static string TrayIconTextFormat {
            get {
                return ResourceManager.GetString("TrayIconTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TrayLanguageItem {
            get {
                return ResourceManager.GetString("TrayLanguageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Unlocker.
        /// </summary>
        public static string TrayShowItem {
            get {
                return ResourceManager.GetString("TrayShowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileLockCheck.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
